language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  # - jruby
  # - rbx
before_install:
  - gem update bundler
install: bundle install --retry=3
sudo: false
addons:
  code_climate:
    repo_token: 5e3e0f72f98a8345473dac4f2a2e2c980509d57ed1fa87725f3dcc299da0f795
