language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.2
  - jruby
  - rbx

install: bundle install --retry=3

addons:
  code_climate:
    repo_token: 5e3e0f72f98a8345473dac4f2a2e2c980509d57ed1fa87725f3dcc299da0f795
